// Generated by CoffeeScript 1.7.1
(function() {
  var clean, fold, groupFromEvent, onlyOne, onlySwedish, sortByName, _;

  _ = require('lodash');

  groupFromEvent = function(data) {
    return _.map(data, function(event) {
      return event.league;
    });
  };

  onlySwedish = function(data) {
    return _.filter(data, function(name) {
      return name === 'Allsvenskan' || name === 'Superettan' || name === 'Division 1 Norra';
    });
  };

  onlyOne = function(data) {
    return _.unique(data);
  };

  sortByName = function(data) {
    return data.sort();
  };

  fold = function(data) {
    return _.reduce(data, function(names, name) {
      return names + ', ' + name;
    });
  };

  clean = function(data) {
    if (data != null) {
      return data.replace(/,([^,]*)$/, " &$1");
    } else {
      return "No Result";
    }
  };

  module.exports = {
    swedish: _.compose(clean, fold, sortByName, onlyOne, onlySwedish, groupFromEvent),
    all: _.compose(clean, fold, sortByName, onlyOne, groupFromEvent),
    raw: _.compose(groupFromEvent),
    groupFromEvent: groupFromEvent,
    onlySwedish: onlySwedish,
    onlyOne: onlyOne,
    sortByName: sortByName,
    fold: fold,
    clean: clean
  };

}).call(this);
